src/objects/Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Feedback__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contribution</label>
    <nameField>
        <label>Contribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <recordTypes>
        <fullName>Feedback</fullName>
        <active>true</active>
        <label>Feedback</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FieldsetListController.cls
global class FieldsetListController extends VisualEditor.DynamicPickList{
	global override VisualEditor.DataRow getDefaultValue(){
        VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('None',''); 
        return defaultValue;
    }
    global override VisualEditor.DynamicPickListRows getValues(){
        Schema.SObjectType sObj = Schema.getGlobalDescribe().get('Contribution__c');
        VisualEditor.DynamicPickListRows pickListValues = new VisualEditor.DynamicPickListRows();
        for(Schema.FieldSet FS : sObj.getDescribe().fieldSets.getMap().values()){
            VisualEditor.DataRow pickListRowValue = new VisualEditor.DataRow(fs.getLabel()+' Contribution', fs.getName());
            pickListValues.addRow(pickListRowValue);
        }
        sObj = Schema.getGlobalDescribe().get('Feedback__c');
        for(Schema.FieldSet FS : sObj.getDescribe().fieldSets.getMap().values()){
            VisualEditor.DataRow pickListRowValue = new VisualEditor.DataRow(fs.getLabel()+' Feedback', fs.getName());
            pickListValues.addRow(pickListRowValue);
        }
        return pickListValues;
    }
}