src/objects/Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pillars__c</fullName>
        <label>Categories</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expertise</fullName>
                </value>
                <value>
                    <fullName>Generosity</fullName>
                </value>
                <value>
                    <fullName>Leadership</fullName>
                </value>
                <value>
                    <fullName>Advocacy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contribution</label>
    <nameField>
        <label>Contribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Advocacy_Rating__c</fullName>
        <label>Advocacy (Rating)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expertise_Rating__c</fullName>
        <label>Expertise (Rating)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generosity_Rating__c</fullName>
        <label>Generosity (Rating)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leadership_Rating__c</fullName>
        <label>Leadership (Rating)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nominator__c</fullName>
        <label>Nominator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Feedbacks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <recordTypes>
        <fullName>Feedback</fullName>
        <active>true</active>
        <label>Feedback</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/subChildController.cls
public with sharing class subChildController {
	@AuraEnabled
    public static Integer createContribution(Id id){
        Integer count;
        Feedback__c feedback = [SELECT Id, Advocacy_Rating__c, Date__c, Expertise_Rating__c, Name, Generosity_Rating__c, Leadership_Rating__c, Nominator__c, Status__c FROM Feedback__c WHERE Id=:id];
		Contribution__c contri = new Contribution__c();
        contri.Contact__c = feedback.Nominator__c;
        List<String> categ = new List<String>();
        if(feedback.Advocacy_Rating__c != null && feedback.Advocacy_Rating__c > 0){
            categ.add('Advocacy');
        }
        if(feedback.Expertise_Rating__c != null && feedback.Expertise_Rating__c > 0){
            categ.add('Expertise');
        }
        if(feedback.Generosity_Rating__c != null && feedback.Generosity_Rating__c > 0){
            categ.add('Generosity');
        }
        if(feedback.Leadership_Rating__c != null && feedback.Leadership_Rating__c > 0){
            categ.add('Leadership');
        }
        String categories;
        if(categ.size() > 1){
        	categories = String.join(categ,';');
        } else if(categ.size() == 1){
            categories = categ[0];
        } 
        
        contri.Pillars__c = categories;
        contri.Name = feedback.Id + 'contribution';
        contri.Date__c = Date.today();
        contri.Feedback__c = id;
        try{
            insert contri;
            System.debug('Inserted successfully with id'+ contri.Id);
        } catch(Exception e){
            System.debug(e.getMessage());
        }
        String q = 'Select count(Id) Amount from Contribution__c where Contact__r.Id=\''+Feedback.Nominator__c+'\'';
        System.debug('query:'+q);
        List<AggregateResult> temp = Database.query(q);
        count = (Integer)temp[0].get('Amount');     
        System.debug('Count is: '+count);
        return count;
    }
}